Repository micronaut-projects/micronaut-openapi, pull requests merged in 2020-09, with the labels that each got.

#317 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#316 [openapi] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#223 Upgrade to Micronaut 2.x
  build.gradle
  docs-examples/example-groovy/build.gradle
  docs-examples/example-groovy/src/test/groovy/io/micronaut/configuration/openapi/docs/controllers/HelloController.groovy
  docs-examples/example-groovy/src/test/groovy/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.groovy
  docs-examples/example-java/build.gradle
  docs-examples/example-java/src/test/java/io/micronaut/configuration/openapi/docs/controllers/HelloController.java
  docs-examples/example-java/src/test/java/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.java
  docs-examples/example-kotlin/build.gradle
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/configuration/openapi/docs/controllers/HelloController.kt
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.kt
  gradle.properties
  openapi/build.gradle
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
Labels: status: future consideration

#324 Change the group id of the openapi dependency
  src/main/docs/guide/gettingStarted.adoc
Labels: type: docs

#326 Dependency upgrades
  docs-examples/example-kotlin/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#335 Dependency upgrades
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#341 [openapi] Update common files for branch 2.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#340 [openapi] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build
