Repository micronaut-projects/micronaut-openapi, pull requests merged in 2021-02, with the labels that each got.

#450 [openapi] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#451 doc: Extract OpenAPI Definition
  src/main/docs/guide/gettingStarted.adoc
  src/main/docs/guide/openApiDefinition.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#453 Dependency upgrades
  build.gradle
  docs-examples/example-kotlin/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#459 [openapi] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#464 [openapi] Update common files for branch master
  .github/workflows/bintray-publish.yml
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  MAINTAINING.md
Labels: relates-to: build

#466 [openapi] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#461 Dependency upgrades
  docs-examples/example-groovy/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#470 [openapi] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#474 [openapi] Update common files for branch master
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
