Repository micronaut-projects/micronaut-openapi, pull requests merged in 2022-06, with the labels that each got.

#738 Remove generating empty parameters array
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/AnnotationRetentionPolicyTransformerSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOutputYamlSpec.groovy
Labels: type: improvement

#737 Fixed lost tags block in openAPI, when tags described on operation level
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/AnnotationRetentionPolicyTransformerSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationTagsSpec.groovy
Labels: type: improvement

#739 Fixed encoding style parameter. Fix lost schema ref
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEncodingSpec.groovy
Labels: type: improvement

#740 doc: fix markdown table
  SECURITY.md
Labels: relates-to: build

#741 [openapi] Update common files for branch master
  .editorconfig
  .gitattributes
Labels: relates-to: build

#743 Added support ExternalDocumentation annotation
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEncodingSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiExternalDocsSpec.groovy
Labels: type: enhancement

#752 [openapi] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build
