Repository micronaut-projects/micronaut-openapi, pull requests merged in 2022-07, with the labels that each got.

#758 Duplicate managed-swagger depenedency for core compatibility
  gradle/libs.versions.toml
Labels: relates-to: build

#761 Smarter processing of javadoc comments into OpenAPI documentation
  gradle/libs.versions.toml
  openapi/build.gradle
  openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocDescription.java
  openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocParser.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
  openapi/src/test/groovy/io/micronaut/openapi/javadoc/JavadocParserSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationWithjavadocSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRecordsSpec.groovy
Labels: type: enhancement

#765 [openapi] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#782 Expose libraries required for Groovy projects
  gradle.properties
  gradle/libs.versions.toml
  openapi/build.gradle
Labels: type: bug
