Repository micronaut-projects/micronaut-openapi, pull requests merged in 2022-05, with the labels that each got.

#701 [openapi] Update common files for branch master
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  MAINTAINING.md
Labels: relates-to: build

#725 ci: project version to 4.1.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#726 [openapi] Update common files for branch master
  .github/workflows/graalvm.yml
Labels: relates-to: build

#723 Add io.micronaut.http.HttpHeaders class to ignore
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiHttpHeadersSpec.groovy
Labels: type: improvement

#721 Fixed wrong content block, when response without content
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEmptyBodyResponseSpec.groovy
Labels: type: bug

#728 Fixed urls with complex URI Path Variables
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPathParamRegexSpec.groovy
Labels: type: improvement

#732 Line endings
  .gitattributes
  gradlew.bat
Labels: relates-to: build

#733 build: Add a bom and use micronaut catalog
  docs-examples/example-groovy/build.gradle
  docs-examples/example-java/build.gradle
  docs-examples/example-kotlin/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  openapi-bom/build.gradle
  openapi/build.gradle
  settings.gradle
Labels: relates-to: build
