Repository micronaut-projects/micronaut-openapi, pull requests merged in 2022-11, with the labels that each got.

#808 [openapi] Update common files for branch master
  .gitattributes
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#840 Add ability to customize classes schemas in properties.
  gradle.properties
  gradle/libs.versions.toml
  gradle/license.gradle
  openapi/openapi-custom-schema-for-class.properties
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/JAXBElement.java
  openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement.java
  openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement2.java
  openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement3.java
  openapi/src/test/groovy/io/micronaut/openapi/ObjectId.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenapiCustomSchemaSpec.groovy
  openapi/src/test/resources/application-schemaforclass.yml
  src/main/docs/guide/customSerializers.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#848 [openapi] Update common files for branch master
  .github/workflows/graalvm.yml
Labels: relates-to: build

#851 Added processing Schema attributes, when it used with implementation.
  gradle.properties
  gradle/libs.versions.toml
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaPrimitiveTypeSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/SchemaMetaAnnotationSpec.groovy
Labels: type: bug

#860 ci: junit-report@v3.6.1 slsa 1.3.0 and Gradle 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
