Repository micronaut-projects/micronaut-openapi, pull requests merged in 2023-08, with the labels that each got.

#1164 Fix version select options in gh-pages
  5.0.0-M10/guide/index.html
  5.0.0-M11/guide/index.html
  5.0.0-M12/guide/index.html
  5.0.0-M2/guide/index.html
  5.0.0-M3/guide/index.html
  5.0.0-M4/guide/index.html
  5.0.0-M5/guide/index.html
  5.0.0-M6/guide/index.html
  5.0.0-M7/guide/index.html
  5.0.0-M8/guide/index.html
  5.0.0-M9/guide/index.html
  5.0.x/guide/index.html
  5.1.0/guide/index.html
  5.1.x/guide/index.html
  latest/guide/index.html
Labels: type: docs

#1151 [openapi] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1170 element.getValue(..., String.class) -> element.stringValue(...)
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy
Labels: type: bug
