Repository micronaut-projects/micronaut-openapi, pull requests merged in 2023-07, with the labels that each got.

#1093 [openapi] Update common files for branch master
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#1108 OpenAPI to Micronaut Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#1115 Add ability to set project directory.
  gradle/libs.versions.toml
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
  src/main/docs/guide/customSerializers.adoc
  src/main/docs/guide/exposingSwaggerOutput.adoc
  src/main/docs/guide/kotlin.adoc
  src/main/docs/guide/openApiViews/mappingPath.adoc
  src/main/docs/guide/openApiViews/rapidoc.adoc
  src/main/docs/guide/openApiViews/redoc.adoc
  src/main/docs/guide/openApiViews/swaggerui.adoc
  src/main/docs/guide/openApiViews/swaggerui/oauth2.adoc
  src/main/docs/guide/schemaDecorators.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/guide/versionsAndGroups/groups.adoc
  src/main/docs/guide/versionsAndGroups/versions.adoc
Labels: type: improvement

#1138 [openapi] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  MAINTAINING.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build
