Repository micronaut-projects/micronaut-openapi, pull requests merged in 2024-07, with the labels that each got.

#1610 Add support extra Schemas
  openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIExtraSchema.java
  openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIExtraSchemas.java
  openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
  openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
  openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
  openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
  openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
  openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ContextProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ContextUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ElementUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/FileUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiConfigProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiExtraSchemaVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/StringUtil.java
  openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
  openapi/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  openapi/src/test/groovy/io/micronaut/openapi/extra/ExtraModel1.java
  openapi/src/test/groovy/io/micronaut/openapi/extra/ExtraModel2.java
  openapi/src/test/groovy/io/micronaut/openapi/extra/internal/ExtraModelInternalPackage.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApi31Spec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiExtraSchemaVisitorSpec.groovy
  src/main/docs/guide/micronautOpenApiAnnotations/openapiextraschema.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#1614 OpenAPI Generator 7.7.0
  gradle/libs.versions.toml
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/common/params/validation.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/params/validation.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/params/validation_field.mustache
Labels: type: dependency-upgrade

#1633 [openapi] Update common files for branch 6.11.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
