Repository micronaut-projects/micronaut-openapi, pull requests merged in 2025-07, with the labels that each got.

#2255 [openapi] Update common files for branch 6.18.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#2252 Fixed swagger operation annotation without responses
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/operationAnnotations.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
  openapi-generator/src/test/resources/3_0/enum-in-multipart.yml
  openapi-generator/src/test/resources/3_0/multipart-without-response.yml
Labels: type: bug

#2257 Fixed custom schema name with JsonUnwrapped
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJsonUnwrappedSpec.groovy
Labels: type: bug

#2265 [openapi] Update common files for branch 6.18.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2286 Fixed OpenAPIExtraSchema annotation javadoc
  openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIExtraSchema.java
Labels: type: docs

#2285 Fixed Unused schema in combination with OpenAPIGroup and self referencing / recursive schema
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiGroupSpec.groovy
Labels: type: bug
