Repository micronaut-projects/micronaut-openapi, pull requests merged in 2025-06, with the labels that each got.

#2174 Update UI scripts
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2172 Fixed process byte array
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
Labels: type: bug

#2170 Fixed processing java records with kotlin / groovy processors
  openapi/src/main/java/io/micronaut/openapi/visitor/ElementUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerKotlinSpec.groovy
  openapi/src/test/java/io/micronaut/sample/FooRecord.java
Labels: type: bug

#2173 Added support JvmOverloads, JvmRecord and java compatibility annotations for kotlin generator
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/Authorization.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/AuthorizationFilter.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/enum.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/pojo.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
Labels: type: improvement

#2167 Add ability to generate EnumConverterConfig - converters for endpoint parameters
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorOptionsBuilder.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/EnumConverterConfig.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/EnumConverterConfig.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
Labels: type: improvement

#2178 Fixed EnumConverterConfig: added lost import when used lombok
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/EnumConverterConfig.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/EnumConverterConfig.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
Labels: type: bug

#2196 [openapi] Update common files for branch 6.16.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2190 Fixed error with spring boot actuator prometheus endpoint.
  gradle/libs.versions.toml
  openapi/build.gradle
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ContextProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ElementUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/management/EndpointUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/management/EndpointsConfig.java
  openapi/src/main/java/io/micronaut/openapi/visitor/management/SpringActuatorConfigUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/management/SpringActuatorUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEndpointVisitorSpec.groovy
  openapi/src/test/resources/application-spring-actuator2.yml
  test-suite-java-spring/build.gradle
  test-suite-java-spring/src/main/resources/application.yml
Labels: type: bug

#2225 [openapi] Update common files for branch 6.17.x
  .github/workflows/central-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#2207 Remove duplicate schemas in oneOf block considering parent schemas.
  build-logic/src/main/groovy/io.micronaut.build.internal.openapi-base.gradle
  build-logic/src/main/groovy/io.micronaut.build.internal.openapi-test-java.gradle
  docs-examples/example-java/build.gradle
  docs-examples/example-kotlin/build.gradle
  openapi-adoc/build.gradle
  openapi-adoc/src/main/java/io/micronaut/openapi/adoc/OpenApiToAdocConverter.java
  openapi-common/build.gradle
  openapi-generator/build.gradle
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiJacksonVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiNormalizeUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SecurityUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/TagUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOneOfSchemaSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy
  test-suite-java-spring/build.gradle
  test-suite-kotlin-kapt-client-generator/build.gradle
  test-suite-kotlin-kapt-server-generator/build.gradle
  test-suite-kotlin-ksp-client-generator/build.gradle
  test-suite-kotlin-ksp-server-generator/build.gradle
Labels: type: bug

#2235 Fixed Enum Case Sensitivity with non string values
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/enum.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
Labels: type: bug

#2239 Fixed kotlin generator bugs
  gradle/libs.versions.toml
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
Labels: type: bug
