Repository micronaut-projects/micronaut-openapi, pull requests merged in 2025-04, with the labels that each got.

#2064 Added `noArgsConstructor` property to generate no-args constructor with required-args constructor
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerOptionsBuilder.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
Labels: type: enhancement

#2072 Fix merge generated spec with additional openapi spec files
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiMergeSchemaSpec.groovy
  openapi/src/test/resources/application-additional-files2.yml
  openapi/src/test/resources/application-additional-files3.yml
  openapi/src/test/resources/merge/diff-media-type.yml
  openapi/src/test/resources/merge/option-endpoints.yml
Labels: type: bug

#2063 New feature: Automatic Tag generation by controller class name or/and package name
  build-logic/src/main/groovy/io/micronaut/build/internal/openapi/OpenApiGeneratorTask.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ContextProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/EndpointsConfiguration.java
  openapi/src/main/java/io/micronaut/openapi/visitor/GeneratorUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiConfigProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/StringUtil.java
  openapi/src/main/java/io/micronaut/openapi/visitor/TagUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
  openapi/src/test/groovy/io/micronaut/openapi/javadoc/JavadocParserSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRecordsSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiTagGenerationSpec.groovy
  src/main/docs/guide/configuration/availableOptions.adoc
  src/main/docs/guide/mergingSchemas.adoc
  src/main/docs/guide/namingStrategy.adoc
  src/main/docs/guide/tagsGeneration.adoc
  src/main/docs/guide/toc.yml
  test-suite-generator-util/src/main/java/io/micronaut/openapi/testsuite/GeneratorMain.java
Labels: type: enhancement

#2080 Improving Spring Boot support: Correctly interpret endpoints with multipart form data
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ElementUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadSpec.groovy
  test-suite-java-spring/src/main/java/io/micronaut/openapi/spring/api/HelloController.java
Labels: type: improvement

#2106 [openapi] Update common files for branch 6.16.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
