Repository micronaut-projects/micronaut-openapi, pull requests merged in 2025-05, with the labels that each got.

#2113 [openapi] Update common files for branch 6.16.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#2124 Fix required args construct generation in client POJO's, when some properties are readOnly
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/resources/3_0/oas.yml
Labels: type: bug

#2100 Replace reserved word `application` to `Application`
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
Labels: type: bug

#2091 Added support `useTags` property. Added ability to set `generateOperationOnlyForFirstTag` property
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorOptionsBuilder.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
Labels: type: enhancement

#2131 Fix `resultSchemaName` not checking all existing class entries
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  test-suite-java-jaxrs/src/test/java/io/micronaut/openapi/jaxrs/ModelController.java
  test-suite-java-jaxrs/src/test/java/io/micronaut/openapi/jaxrs/ModelControllerTest.java
  test-suite-java-jaxrs/src/test/java/io/micronaut/openapi/jaxrs/model/one/Response.java
  test-suite-java-jaxrs/src/test/java/io/micronaut/openapi/jaxrs/model/two/Response.java
Labels: type: bug

#2135 Add ability to enable/disable JDK URLConnectionCache
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautCodegenTest.java
Labels: type: enhancement

#2143 Fixed default values for multipart-data parameters and swagger2
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
  openapi-generator/src/test/resources/3_0/micronaut/content-type.yml
  openapi-generator/src/test/resources/3_0/micronaut/multi-tags-test.yml
  openapi-generator/src/test/resources/3_0/micronaut/oauth2.yml
  openapi-generator/src/test/resources/3_0/micronaut/roles-extension-test.yml
  openapi-generator/src/test/resources/3_0/multipartdata.yml
  openapi-generator/src/test/resources/3_0/parameter-list-with-default-swagger2.yml
  openapi-generator/src/test/resources/3_0/parameter-list-with-default.yml
  openapi-generator/src/test/resources/petstore.yml
Labels: type: bug

#2144 Add support `@Format` annotation to identify query parameter style
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/GroupUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/MnParamFormat.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ParamUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SecurityUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationWithjavadocSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiQueryValueWithFormatSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy
Labels: type: improvement

#2142 Fix body unwrapped parameter
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/model/one/Response.java
  openapi/src/test/groovy/io/micronaut/openapi/model/two/Response.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
Labels: type: bug

#2147 Update UI scripts
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2146 Remove information about required `@OpenAPIDefinition` annotation
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  src/main/docs/guide/openApiDefinition.adoc
Labels: type: docs

#2077 Improvements for swagger 2.2.32
  gradle/libs.versions.toml
  openapi-common/src/main/java/io/micronaut/openapi/SimpleSchema.java
  openapi-common/src/main/java/io/micronaut/openapi/swagger/core/util/ModelDeserializer.java
  openapi-common/src/main/java/io/micronaut/openapi/swagger/core/util/PrimitiveType.java
  openapi/src/main/java/io/micronaut/openapi/introspections/MediaConfiguration.java
  openapi/src/main/java/io/micronaut/openapi/postprocessors/JacksonDiscriminatorPostProcessor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiNormalizeUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ProtoUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadBodyParameterSpec.groovy
Labels: type: improvement, type: dependency-upgrade

#2149 For kotlin and KSP we can use non-nullable types for properties / parameters with default value
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/params/validation.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/common/params/validation_field.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
  openapi-generator/src/test/resources/3_0/default-value-optional.yml
Labels: type: improvement

#2156 [openapi] Update common files for branch 6.16.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#2145 Add support query parameters style to generate `@Format` annotation
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/main/resources/templates/java-micronaut/client/params/type.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/server/params/type.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/type.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/server/controller-interface.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
  openapi-generator/src/test/resources/3_0/params-with-style.yml
Labels: type: improvement

#2132 Improvements for authorization classes generation.
  openapi-generator/src/main/java/io/micronaut/openapi/generator/AuthFilterPatternStyle.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerOptionsBuilder.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
  openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
  openapi-generator/src/main/resources/templates/java-micronaut/client/api.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/Authorization.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/AuthorizationBinder.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/AuthorizationFilter.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/Authorizations.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/config/ApiKeyAuthConfig.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/config/ConfigurableAuthorization.mustache
  openapi-generator/src/main/resources/templates/java-micronaut/client/auth/config/HttpBasicAuthConfig.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/api.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/Authorization.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/AuthorizationBinder.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/AuthorizationFilter.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/Authorizations.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/config/ApiKeyAuthConfig.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/config/ConfigurableAuthorization.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/auth/config/HttpBasicAuthConfig.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/cookieParams.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/headerParams.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/pathParams.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/client/params/queryParams.mustache
  openapi-generator/src/main/resources/templates/kotlin-micronaut/server/params/annotations.mustache
  openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
  openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
  openapi-generator/src/testFixtures/java/io/micronaut/openapi/generator/assertions/TestUtils.java
  test-suite-java-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
  test-suite-kotlin-kapt-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
  test-suite-kotlin-ksp-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
Labels: type: improvement

#2163 Fix process interfaces with inheritance
  openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
Labels: type: bug
