Repository micronaut-projects/micronaut-openapi, pull requests merged in 2025-09, with the labels that each got.

#2337 Added support JsonInclude annotation and added ability to set default JsonInclude mode
  gradle.properties
  openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/FileUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiConfigProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
  src/main/docs/guide/configuration/availableOptions.adoc
Labels: type: enhancement

#2343 Added ability to set patterns (and exclude patterns) for additional files.
  openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
  openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ContextProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/FileUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
  openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiConfigProperty.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaDefinitionUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
  openapi/src/main/java/io/micronaut/openapi/visitor/UrlUtils.java
  openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiMergeSchemaSpec.groovy
  openapi/src/test/resources/openapi/excluded/openapi-excluded-service1.yml
  openapi/src/test/resources/openapi/included/openapi-service1.yml
  openapi/src/test/resources/openapi/openapi-service0.yml
  src/main/docs/guide/configuration/availableOptions.adoc
Labels: type: improvement

#2310 [openapi] Update common files for branch 6.18.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradlew
Labels: relates-to: build

#2355 Added lost Spring Boot Actuator endpoints: `configprops` and `conditions`
  openapi/src/main/java/io/micronaut/openapi/visitor/management/EndpointUtils.java
  test-suite-spring-java/src/main/resources/application.yml
  test-suite-spring-kotlin-kapt/src/main/resources/application.yml
  test-suite-spring-kotlin-ksp/src/main/resources/application.yml
Labels: type: bug
